=== mr-yhl/javajybc/day18/homework/bookshelf.dtd
<?xml version="1.0" encoding="UTF-8"?>
    <!--
    传智播客DTD教学实例文档，将注释中的以下内容复制到要编写的xmL的声明下面
    复制内容如下：
    <!DOCTYPE books SYSTEM "bookshelf.dtd">
    -->
<!ELEMENT books (book+)>
<!ELEMENT book (name,author,date,price)><!--约束元素书的子元素必须为书名、作者、售价-->
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== mr-yhl/javajybc/day18/homework/books.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE books SYSTEM "bookshelf.dtd">
<books>
    <book>
        <name>架构师成长之路</name>
        <author>黑马程序员</author>
        <date>2010-6-6</date>
        <price>125.00</price>
    </book>
    <book>
        <name>JavaEE企业级开发</name>
        <author>黑马研究院</author>
        <date>2011-5-5</date>
        <price>115.80</price>
    </book>
    <book>
        <name>Oracle指南</name>
        <author>黑马程序员</author>
        <date>清华计算机</date>
        <price>89.00</price>
    </book>
</books>
